apiVersion: v1
kind: Pod
metadata:
  name: builder
spec:
  containers:
    - name: dind-daemon
      image: docker:dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
      args:
          - "--insecure-registry=kind-registry:5000"
    - name: builder
      image: localhost:5001/builder:0.3
      env:
        - name: DOCKER_HOST
          value: "tcp://localhost:2375"
      command:
      - cat
      tty: true

